management/urls.py
from django.urls import path

from .views import EarningCreateview, EarningUpdateview, EarningDeleteview,\
    ExpenseCreateview, ExpenseUpdateview, ExpenseDeleteview, DebtCreateview,\
    DebtUpdateview, DebtDeleteview, InvestmentCreateview, InvestmentUpdateview,\
    InvestmentDeleteview, DashboardCreateview

app_name = 'management'

urlpatterns = [
    path('dashboard', DashboardCreateview.as_view(), name='dashboard'),

    path('earning', EarningCreateview.as_view(), name="earnings"),
    path('earning/edit/<int:pk>', EarningUpdateview.as_view(), name="earnings_edit"),
    path('earning/delete/<int:pk>', EarningDeleteview.as_view(), name="earnings_delete"),

    path('expense', ExpenseCreateview.as_view(), name="expenses"),
    path('expense/edit/<int:pk>', ExpenseUpdateview.as_view(), name="expenses_edit"),
    path('expense/delete/<int:pk>', ExpenseDeleteview.as_view(), name="expenses_delete"),

    path('debt_management', DebtCreateview.as_view(), name="debt"),
    path('debt/edit/<int:pk>', DebtUpdateview.as_view(), name="debt_edit"),
    path('debt/delete/<int:pk>', DebtDeleteview.as_view(), name="debt_delete"),

    path('investment', InvestmentCreateview.as_view(), name="investment"),
    path('investment/edit/<int:pk>', InvestmentUpdateview.as_view(), name="investment_edit"),
    path('investment/delete/<int:pk>', InvestmentDeleteview.as_view(), name="investment_delete"),
]

personal_finance/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('management.urls', namespace='management')),
    path('', RedirectView.as_view(url='accounts/login')),
]

management/models.py
from django.db import models
from django.contrib.auth.models import User


class Debt(models.Model):
    """
    Represent Debt per User
    """
    DEBT_CATEGORY = (
        ("Short Term", "Short Term"),
        ("Long Term", "Long Term")
    )

    user = models.ForeignKey(User, related_name="debts", on_delete = models.CASCADE)
    category = models.CharField(
        max_length = 100,
        choices = DEBT_CATEGORY,
        default = "Short Term"
    )
    # interest_rate is decimal field like 5.00%, and its monthly rate by assuming
    interest_rate = models.DecimalField(default=0.0, max_digits=5, decimal_places=2)
    amount = models.PositiveIntegerField(default=0)
    start_date = models.DateField()
    end_date = models.DateField(blank=True, null=True)
    notes = models.TextField(blank=True, null=True)

    created_dt = models.DateTimeField(auto_now_add=True)
    updated_dt = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['amount']

    def __str__(self):
        return str(self.amount) + " (rate: " + str(self.interest_rate) + ")"
    

class Expense(models.Model):
    """
    Represent Expense per User
    """
    EXPENSE_PERIOD = (
        ("One Time", "One Time"),
        ("Weekly", "Weekly"),
        ("Bi-Weekly", "Bi-Weekly"),
        ("Monthly", "Monthly"),
        ("Annually", "Annually")
    )
    EXPENSE_CATEGORY = (
        ("Debt", "Debt"),
        ("Food", "Food"),
        ("Electricity", "Electricity"),
        ("Car", "Car"),
        ("Petrol", "Petrol"),
        ("Property", "Property"),
        ("Other", "Other")
    )

    user = models.ForeignKey(User, related_name="expenses", on_delete = models.CASCADE)
    category = models.CharField(
        max_length = 100,
        choices = EXPENSE_CATEGORY,
        default = "Other"
    )
    period = models.CharField(
        max_length = 100,
        choices = EXPENSE_PERIOD,
        default = "One Time"
    )
    debt = models.ForeignKey(Debt, related_name="debts", on_delete = models.CASCADE, default=0)
    amount = models.PositiveIntegerField(default=0)
    payment_start_date = models.DateField()
    payment_end_date = models.DateField(blank=True, null=True)
    notes = models.TextField(blank=True, null=True)

    created_dt = models.DateTimeField(auto_now_add=True)
    updated_dt = models.DateTimeField(auto_now=True)


class Investment(models.Model):
    """
    Represent Investment Model per User
    """
    INVESTMENT_CATEGORY = (
        ("Stock", "Stock"),
        ("Forex", "Forex"),
        ("Real Estate", "Real Estate"),
        ("Cryptocurrency", "Cryptocurrency"),
        ("Other", "Other")
    )
    user = models.ForeignKey(User, related_name="investments", on_delete = models.CASCADE)
    category = models.CharField(
        max_length = 100,
        choices = INVESTMENT_CATEGORY,
        default = "Other"
    )
    # profit_rate is decimal field like 5.00%, and its monthly rate by assuming
    profit_rate = models.DecimalField(default=0.0, max_digits=5, decimal_places=2)
    amount = models.PositiveIntegerField(default=0)
    start_date = models.DateField()
    end_date = models.DateField(blank=True, null=True)
    notes = models.TextField(blank=True, null=True)

    created_dt = models.DateTimeField(auto_now_add=True)
    updated_dt = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.amount) + " (rate: " + str(self.profit_rate) + ")"


class Earning(models.Model):
    """
    Represent Earning per User
    """
    EARNING_PERIOD = (
        ("One Time", "One Time"),
        ("Weekly", "Weekly"),
        ("Bi-Weekly", "Bi-Weekly"),
        ("Monthly", "Monthly"),
        ("Annually", "Annually")
    )
    EARNING_CATEGORY = (
        ("Normal", "Normal"),
        ("Investment", "Investment")
    )

    user = models.ForeignKey(User, related_name="earnings", on_delete = models.CASCADE)
    category = models.CharField(
        max_length = 100,
        choices = EARNING_CATEGORY,
        default = "Normal"
    )
    period = models.CharField(
        max_length = 100,
        choices = EARNING_PERIOD,
        default = "One Time"
    )
    investment = models.ForeignKey(Investment, related_name="investments", on_delete = models.CASCADE, default=0)
    amount = models.PositiveIntegerField(default=0)
    payment_start_date = models.DateField()
    payment_end_date = models.DateField(blank=True, null=True)
    notes = models.TextField(blank=True, null=True)

    created_dt = models.DateTimeField(auto_now_add=True)
    updated_dt = models.DateTimeField(auto_now=True)


class Transaction(models.Model):
    """
    Represent Investment Model per User
    """
    TRANSACTION_CATEGORY = (
        ("Earning", "Earning"),
        ("Expense", "Expense"),
        ("Debt", "Debt"),
        ("Investment", "Investment")
    )
    user = models.ForeignKey(User, related_name="transactions", on_delete = models.CASCADE)
    category = models.CharField(
        max_length = 100,
        choices = TRANSACTION_CATEGORY,
        default = "Earning"
    )
    amount = models.IntegerField(default=0)
    payment_date = models.DateField(blank=True, null=True)
    notes = models.TextField(blank=True, null=True)
    
    created_dt = models.DateTimeField(auto_now_add=True)
    updated_dt = models.DateTimeField(auto_now=True)

templates/expense/create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}

<h1>Expense Page</h1>
{% crispy form %}

<div class="mt-2">
  <table id="expense_table" class="table table-striped" style="width:100%">
    <thead>
      <tr>
        <th class="text-center">Category</th>
        <th class="text-center">Period</th>
        <th class="text-center">Amount</th>
        <th class="text-center">Payment Start Date</th>
        <th class="text-center">Payment End Date</th>
        <th class="text-center">Note</th>
        <th class="text-center">Actions</th>
      </tr>
    </thead>
    <tbody>
      {% for expense in expenses %}
      <tr>
        <td class="text-center">{{expense.category}}</td>
        <td class="text-center">{{expense.period}}</td>
        <td class="text-center">{{expense.amount}}</td>
        <td class="text-center">{{expense.payment_start_date}}</td>
        <td class="text-center">{{expense.payment_end_date}}</td>
        <td class="text-center">{{expense.note}}</td>
        <td class="text-center">
          <a class="btn btn-primary" href="expense/edit/{{expense.id}}">Edit</a>
          <a class="btn btn-danger" href="expense/delete/{{expense.id}}">Delete</a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock %}

{% block customJS %}
<script src="{% static 'jquery.dataTables.min.js' %}"></script>
<script src="{% static 'dataTables.bootstrap5.min.js' %}"></script>
<script>
  $(document).ready(function () {
    $("#div_id_debt").hide();
    $("#id_category").change(function(){
      if($(this).val()=="Debt") {
        $("#div_id_period").hide();
        $("#div_id_debt").show();
      } else {
        $("#div_id_period").show();
        $("#div_id_debt").hide();
      }
    });
    $('#expense_table').DataTable();
  });
</script>
{% endblock %}

{% block customCSS %}
<style>
  #expense_table_filter input{
    border: 1px solid #ced4da;
  }
</style>
{% endblock %}