management/urls.py
from django.urls import path

from .views import EarningCreateview, EarningUpdateview, EarningDeleteview,\
    ExpenseCreateview, ExpenseUpdateview, ExpenseDeleteview, DebtCreateview,\
    DebtUpdateview, DebtDeleteview, InvestmentCreateview, InvestmentUpdateview,\
    InvestmentDeleteview, DashboardCreateview

app_name = 'management'

urlpatterns = [
    path('dashboard', DashboardCreateview.as_view(), name='dashboard'),

    path('earning', EarningCreateview.as_view(), name="earnings"),
    path('earning/edit/<int:pk>', EarningUpdateview.as_view(), name="earnings_edit"),
    path('earning/delete/<int:pk>', EarningDeleteview.as_view(), name="earnings_delete"),

    path('expense', ExpenseCreateview.as_view(), name="expenses"),
    path('expense/edit/<int:pk>', ExpenseUpdateview.as_view(), name="expenses_edit"),
    path('expense/delete/<int:pk>', ExpenseDeleteview.as_view(), name="expenses_delete"),

    path('debt_management', DebtCreateview.as_view(), name="debt"),
    path('debt/edit/<int:pk>', DebtUpdateview.as_view(), name="debt_edit"),
    path('debt/delete/<int:pk>', DebtDeleteview.as_view(), name="debt_delete"),

    path('investment', InvestmentCreateview.as_view(), name="investment"),
    path('investment/edit/<int:pk>', InvestmentUpdateview.as_view(), name="investment_edit"),
    path('investment/delete/<int:pk>', InvestmentDeleteview.as_view(), name="investment_delete"),
]

personal_finance/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('management.urls', namespace='management')),
    path('', RedirectView.as_view(url='accounts/login')),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>{% block title %}{% endblock %}</title>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'dataTables.bootstrap5.min.css' %}">
    <link rel="stylesheet" href="{% static 'styles/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'styles/style.css' %}">
    <link rel="stylesheet" href="{% static 'styles/custom.css' %}">
    {% block customCSS %}
    {% endblock %}
    <meta name="robots" content="noindex, follow">
</head>
<body>
  <div class="wrapper d-flex align-items-stretch">
    <nav id="sidebar">
      <div class="img bg-wrap text-center py-4">
        <div class="user-logo">
          <h3>Personal Financial Management</h3>
        </div>
      </div>
      <ul class="list-unstyled components mb-5">
        <li>
          <a href="{% url 'management:dashboard' %}"> Dashboard</a>
        </li>
        <li>
          <a href="{% url 'management:earnings' %}"> Earnings</a>
        </li>
        <li>
          <a href="{% url 'management:expenses' %}"> Expenses</a>
        </li>
        <li>
          <a href="{% url 'management:debt' %}"> Debt Management</a>
        </li>
        <li>
          <a href="{% url 'management:investment' %}"> Investments</a>
        </li>
        <li>
          <a href="{% url 'account_logout' %}"> Sign Out</a>
        </li>
      </ul>
    </nav>

    <div id="content" class="p-4 p-md-5 pt-5">
      {% block content %}
      {% endblock %}
    </div>
  </div>
  <script src="{% static 'jquery.min.js' %}"></script>
  <script src="{% static 'bootstrap.min.js' %}"></script>
  
  {% block customJS %}
  {% endblock %}
</body>
</html>

templates/confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<form method="post">
{% csrf_token %}
  <p>Are you sure you want to delete {{ object.pk }}th item?</p>    
    <input type="submit" value="Confirm">
</form>

{% endblock %}

templates/dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

  <h1>Dashboard</h1>
  <h3>Cash Flow</h3>
  <div id="cash_chart"></div>
  <h3>Debt</h3>
  <div id="debt_chart"></div>
  <h3>Investment</h3>
  <div id="investment_chart"></div>

{% endblock %}

{% block customJS %}
  <script src="{% static 'highcharts/highcharts.js' %}"></script>
  <script src="{% static 'highcharts/modules/series-label.js' %}"></script>
  <script src="{% static 'highcharts/modules/exporting.js' %}"></script>
  <script src="{% static 'highcharts/modules/export-data.js' %}"></script>
  <script src="{% static 'highcharts/modules/accessibility.js' %}"></script>
  <script type="text/javascript">
    Highcharts.chart('cash_chart', {
      chart: {
        type: 'column'
      },
    
      title: {
        text: ''
      },
    
      subtitle: {
        text: ''
      },
    
      xAxis: {
        categories: {{dates}},
        labels: {
          x: -10
        },
        title: {
          text: 'Day'
        }
      },
    
      yAxis: {
        allowDecimals: false,
        title: {
          text: 'Amount'
        }
      },
    
      series: [
        {
          name: 'Earning',
          data: {{earning_data}}
        },
        {
          name: 'Expense',
          data: {{expense_data}}
        }
      ],

      credits:{
        enabled: false
      },

      exporting: { 
        enabled: false
      },

      responsive: {
        rules: [
          {
            condition: {
              maxWidth: 500
            },
            chartOptions: {
              legend: {
                align: 'center',
                verticalAlign: 'bottom',
                layout: 'horizontal'
              },
              yAxis: {
                labels: {
                  align: 'left',
                  x: 0,
                  y: -5
                },
                title: {
                  text: null
                }
              },
              subtitle: {
                text: null
              },
              credits: {
                enabled: false
              }
            }
          }
        ]
      }
    })

    Highcharts.chart('debt_chart', {
      title: {
        text: '',
        align: 'left'
      },
      xAxis: {
        categories: {{debts|safe}},
        title: {
          text: 'Item'
        }
      },
      yAxis: {
        title: {
          text: 'Amount'
        }
      },
      tooltip: {
        valueSuffix: ''
      },

      credits:{
        enabled: false
      },

      exporting: { 
        enabled: false
      },

      series: [
        {
          type: 'column',
          name: 'Debt',
          data: {{debt_data}}
        },
        {
          type: 'spline',
          name: 'Payback',
          data: {{debt_expense_data}},
          marker: {
            lineWidth: 2,
            lineColor: Highcharts.getOptions().colors[2],
            fillColor: 'white'
          }
        }
      ]
    });

    Highcharts.chart('investment_chart', {
      title: {
        text: '',
        align: 'left'
      },
      xAxis: {
        categories: {{investments|safe}},
        title: {
          text: 'Item'
        }
      },
      yAxis: {
        title: {
          text: 'Amount'
        }
      },
      tooltip: {
        valueSuffix: ''
      },

      credits:{
        enabled: false
      },

      exporting: { 
        enabled: false
      },

      series: [
        {
          type: 'column',
          name: 'Investment',
          data: {{investment_data}}
        },
        {
          type: 'spline',
          name: 'Payback',
          data: {{investment_earning_data}},
          marker: {
            lineWidth: 2,
            lineColor: Highcharts.getOptions().colors[2],
            fillColor: 'white'
          }
        }
      ]
    });
  </script>
{% endblock %}

templates/update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<h1>{{ title }} Edit Page</h1>
{% crispy form %}

{% endblock %}